### ISSUE TITLE
zsh command is too long when running ECR command

### ISSUE THREAD

**Issue by trystant** [mnyon-grandkru/knowledgebase#84]
When running `"$(aws ecr get-login --region us-west-2 --no-include-email)"` from the command line, the error returned is: 
```
zsh: command too long: docker login -u AWS -p REALLY_LONG_PASSWORD_THAT_GIVES_THE_COMMAND_A_LENGTH_OF_2422_CHARACTERS https://ECR_HOST.amazonaws.com
```

**Comment by mnyon-grandkru** [comment]
So, reading through this [StackOverflow](https://unix.stackexchange.com/questions/606847/argument-list-too-long-in-zsh-with-any-command), it looks like my overall ENV variables may be too high, so my next step on this is to remove environment variables that aren't needed and see if this reduces things.

**Comment by mnyon-grandkru** [comment]
Step: Determine the current env size and determine how to reduce it on MacBook Pro

**Comment by mnyon-grandkru** [comment]
I'm closing this as I've only run into this in relation to my old job.
