### ISSUE TITLE
Error getting semantic-ui dropdowns to work on Rails app

### ISSUE THREAD

**Issue by mnyon-grandkru** [mnyon-grandkru/knowledgebase#95]
A new programmer is currently trying to get semantic-ui working with a Rails 6 and Ruby 3.2.2 app:
> Hi.   i am new to programming and have been following a course,  as part of this i have just started a new project using rail 6.1.7.3 and ruby 3.2.2 with semantic-ui for styling.  i can get semantic working but the dropdowns dont work.  it seems packs/manifest.json is not being created

Error with empty manifest.json
> ActionView::Template::Error (unexpected token at ''):
>    8:     <%= csp_meta_tag %>
>     9: 
>    10:     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
>    11:     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
>    12:   </head>
>    13: 
>   14:   <body>
  
> app/views/layouts/application.html.erb:11

Error message with filled in manifest.json
> Started GET "/packs/js/application-0777f7a506acd75b1bfd.js" for ::1 at 2023-04-30 21:26:03 +0100
>
> ActionController::RoutingError (No route matches [GET] "/packs/js/application-0777f7a506acd75b1bfd.js"):

I've opened up a Rails 6.1.7.3 instance and will try to replicate.

**Comment by Spudos** [comment]
as far as i can understand the problem even though webpacker is installed public/packs/*.json files do not exist which is why i am getting the error when the page tries to load.

i can "fudge" it by creating a manifest.json fine and filling it with boiler plate code but then it looks for the other two .js files in public/packs and doesnt find them so the app runs but returns the error in the console and dropdowns dont work

**Comment by mnyon-grandkru** [comment]
Ah, let's also add the [repo ](https://github.com/EBWiki/EBWiki/pull/4178) while we're at it:

**Comment by mnyon-grandkru** [comment]
hi @Spudos,

How was this resolved? Were you able to create a manifest.json that Rails accepts, or is this still a challenge?

**Comment by mnyon-grandkru** [comment]
Hi @Spudos 

I was looking at your [Gemfile](https://raw.githubusercontent.com/Spudos/chat/master/Gemfile) and noticed that you don't have the [sprockets-rails](https://github.com/rails/sprockets-rails/) gem in the Gemfile. I'd try adding/installing that gem and see if that helps.

**Comment by Spudos** [comment]
ok i will try that.

I think it is my environment that is messed up, probably from installing several versions of rails and not using gemsets to split it all up

**Comment by mnyon-grandkru** [comment]
@Spudos Could you benefit from a screencast on using rvm to separate environments and setup to start? Since we're not due to meet until next week, I figured this may help when you have some downtime over the next few days: https://www.youtube.com/watch?v=cQVb7fHFjSM

**Comment by Spudos** [comment]
thanks i will watch that later
