### ISSUE TITLE
Removing Content from Edge New Tab

### ISSUE THREAD

**Issue by mnyon-grandkru** [mnyon-grandkru/knowledgebase#99]
TL;DR

Before:

![image](https://user-images.githubusercontent.com/5750239/236921899-5b742866-7ae0-4610-9ecc-b262bab3da63.png)

During:

![image](https://user-images.githubusercontent.com/5750239/236921965-78db38b7-dd27-4eec-8730-b20af1fafbab.png)

After:

![image](https://user-images.githubusercontent.com/5750239/236922190-839966b7-d608-48fa-b920-466fc3dd098d.png)

for a longer explanation, the new tab on Edge is noisy and full of information I don't want. I saw @managedkaos sort out how to remove that noise and I decided to preserve it for posterity.

**Comment by managedkaos** [comment]
LGTM! 👍🏿
